apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-shell-access
  namespace: default

spec:
  selector:
    matchLabels:
      app: wisecow

  process:
    matchPaths:
    - path: /bin/sh

  action:
    Block